wandb_version: 1

use_wandb:
  desc: null
  value: true
entity_name:
  desc: null
  value: singfor7012
project_name:
  desc: null
  value: checker-v0
env_name:
  desc: null
  value: ma_gym:Checkers-v0
experiment_name:
  desc: null
  value: ppo
max_episodes:
  desc: null
  value: 60000
max_step:
  desc: null
  value: 100
step_cost:
  desc: null
  value: -0.01
use_render:
  desc: null
  value: false
sleep_second:
  desc: null
  value: 0.0
use_cuda:
  desc: null
  value: false
n_training_threads:
  desc: null
  value: 12
seed:
  desc: null
  value: 42
fix_seed:
  desc: null
  value: true
algorithm_name:
  desc: null
  value: rmappo
share_policy:
  desc: null
  value: true
use_centralized_V:
  desc: null
  value: true
use_linear_lr_decay:
  desc: null
  value: false
log_interval:
  desc: null
  value: 5
use_eval:
  desc: null
  value: true
save_interval:
  desc: null
  value: 1
use_feature_normalization:
  desc: null
  value: true
use_ReLU:
  desc: null
  value: true
stacked_frames:
  desc: null
  value: 1
layer_N:
  desc: null
  value: 1
use_gae:
  desc: null
  value: true
use_proper_time_limits:
  desc: null
  value: false
hidden_size:
  desc: null
  value: 32
use_popart:
  desc: null
  value: false
recurrent_N:
  desc: null
  value: 1
gamma:
  desc: null
  value: 0.99
batch_size:
  desc: null
  value: 1
n_rollout_threads:
  desc: null
  value: 1
n_eval_rollout_threads:
  desc: null
  value: 1
n_render_rollout_threads:
  desc: null
  value: 1
actor_lr:
  desc: null
  value: 0.001
critic_lr:
  desc: null
  value: 0.0005
opti_eps:
  desc: null
  value: 1.0e-05
weight_decay:
  desc: null
  value: 0
gain:
  desc: null
  value: 0.01
use_orthogonal:
  desc: null
  value: true
use_recurrent_policy:
  desc: null
  value: true
use_naive_recurrent_policy:
  desc: null
  value: false
use_max_grad_norm:
  desc: null
  value: true
use_clipped_value_loss:
  desc: null
  value: true
use_huber_loss:
  desc: null
  value: true
use_policy_active_masks:
  desc: null
  value: false
use_value_active_masks:
  desc: null
  value: false
use_valuenorm:
  desc: null
  value: true
clip_param:
  desc: null
  value: 0.2
ppo_epoch:
  desc: null
  value: 15
num_mini_batch:
  desc: null
  value: 1
data_chunk_length:
  desc: null
  value: 10
value_loss_coef:
  desc: null
  value: 1
entropy_coef:
  desc: null
  value: 0.01
max_grad_norm:
  desc: null
  value: 10.0
huber_delta:
  desc: null
  value: 10.0
gae_lambda:
  desc: null
  value: 0.95
eval_interval:
  desc: null
  value: 10
eval_episodes:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1710933389.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.9.18
      5: 0.16.4
      8:
      - 5
      13: linux-x86_64
